import {Platform} from 'react-native';

const textColor = Platform.OS === 'android' ? 'white' : 'black';

export const COUNTRIES = [
    {label: 'Argentina', value: 'Argentina', color: textColor},
    {label: 'Bolivia', value: 'Bolivia', color: textColor},
    {label: 'Chile', value: 'Chile', color: textColor},
    {label: 'Colombia', value: 'Colombia', color: textColor},
    {label: 'Costa Rica', value: 'Costa Rica', color: textColor},
    {label: 'Cuba', value: 'Cuba', color: textColor},
    {label: 'Ecuador', value: 'Ecuador', color: textColor},
    {label: 'El Salvador', value: 'El Salvador', color: textColor},
    {label: 'España', value: 'España', color: textColor},
    {label: 'Estados Unidos', value: 'Estados Unidos', color: textColor},
    {label: 'Guatemala', value: 'Guatemala', color: textColor},
    {label: 'Honduras', value: 'Honduras', color: textColor},
    {label: 'México', value: 'México', color: textColor},
    {label: 'Nicaragua', value: 'Nicaragua', color: textColor},
    {label: 'Panamá', value: 'Panamá', color: textColor},
    {label: 'Paraguay', value: 'Paraguay', color: textColor},
    {label: 'Perú', value: 'Perú', color: textColor},
    {label: 'Puerto Rico', value: 'Puerto Rico', color: textColor},
    {label: 'República Dominicana', value: 'República Dominicana', color: textColor},
    {label: 'Uruguay', value: 'Uruguay', color: textColor},
    {label: 'Venezuela', value: 'Venezuela', color: textColor},
];

export const SPECIALTIES = [
    {label: 'Anatomía patológica', value: 'Anatomía patológica', color: textColor},
    {label: 'Cirugía general y del aparato digestivo', value: 'Cirugía general y del aparato digestivo', color: textColor},
    {label: 'Cirugía ortopédica y traumatología', value: 'Cirugía ortopédica y traumatología', color: textColor},
    {label: 'Hematología y hemoterapia', value: 'Hematología y hemoterapia', color: textColor},
    {label: 'Medicina física y rehabilitación', value: 'Medicina física y rehabilitación', color: textColor},
    {label: 'Medicina intensiva', value: 'Medicina intensiva', color: textColor},
    {label: 'Medicina interna', value: 'Medicina interna', color: textColor},
    {label: 'Medicina nuclear', value: 'Medicina nuclear', color: textColor},
    {label: 'Neurocirugía', value: 'Neurocirugía', color: textColor},
    {label: 'Neurología', value: 'Neurología', color: textColor},
    {label: 'Oncología médica', value: 'Oncología médica', color: textColor},
    {label: 'Oncología radioterápica', value: 'Oncología radioterápica', color: textColor},
    {label: 'Psiquiatría', value: 'Psiquiatría', color: textColor},
    {label: 'Radiodiagnóstico', value: 'Radiodiagnóstico', color: textColor},
    {label: 'Reumatología', value: 'Reumatología', color: textColor},
    {label: 'Urgencias', value: 'Urgencias', color: textColor},

    {label: 'Alergología', value: 'Alergología', color: textColor},
    {label: 'Análisis clínicos', value: 'Análisis clínicos', color: textColor},
    {label: 'Anestesiología y reanimación', value: 'Anestesiología y reanimación', color: textColor},
    {label: 'Angiología y cirugía vascular', value: 'Angiología y cirugía vascular', color: textColor},
    {label: 'Aparato digestivo', value: 'Aparato digestivo', color: textColor},
    {label: 'Bioquímica clínica', value: 'Bioquímica clínica', color: textColor},
    {label: 'Cardiología', value: 'Cardiología', color: textColor},
    {label: 'Cirugía cardiovascular', value: 'Cirugía cardiovascular', color: textColor},
    {label: 'Cirugía oral y maxilofacial', value: 'Cirugía oral y maxilofacial', color: textColor},
    {label: 'Cirugía pediátrica', value: 'Cirugía pediátrica', color: textColor},
    {label: 'Cirugía plástica, estética y reparadora', value: 'Cirugía plástica, estética y reparadora', color: textColor},
    {label: 'Cirugía torácica', value: 'Cirugía torácica', color: textColor},
    {label: 'Dermatología médico-quirúrgica y venereología', value: 'Dermatología médico-quirúrgica y venereología', color: textColor},
    {label: 'Endocrinología y nutrición', value: 'Endocrinología y nutrición', color: textColor},
    {label: 'Farmacología clínica', value: 'Farmacología clínica', color: textColor},
    {label: 'Geriatría', value: 'Geriatría', color: textColor},
    {label: 'Hidrología médica', value: 'Hidrología médica', color: textColor},
    {label: 'Inmunología', value: 'Inmunología', color: textColor},
    {label: 'Medicina de la educación física y el deporte', value: 'Medicina de la educación física y el deporte', color: textColor},
    {label: 'Medicina del trabajo', value: 'Medicina del trabajo', color: textColor},
    {label: 'Medicina familiar y comunitaria', value: 'Medicina familiar y comunitaria', color: textColor},
    {label: 'Medicina legal y forense', value: 'Medicina legal y forense', color: textColor},
    {label: 'Medicina preventiva y salud pública', value: 'Medicina preventiva y salud pública', color: textColor},
    {label: 'Microbiología y parasitología', value: 'Microbiología y parasitología', color: textColor},
    {label: 'Nefrología', value: 'Nefrología', color: textColor},
    {label: 'Neumología', value: 'Neumología', color: textColor},
    {label: 'Neurofisiología clínica', value: 'Neurofisiología clínica', color: textColor},
    {label: 'Obstetricia y ginecología', value: 'Obstetricia y ginecología', color: textColor},
    {label: 'Oftalmología', value: 'Oftalmología', color: textColor},
    {label: 'Otorrinolaringología', value: 'Otorrinolaringología', color: textColor},
    {label: 'Pediatría y sus áreas específicas', value: 'Pediatría y sus áreas específicas', color: textColor},
    {label: 'Urología', value: 'Urología', color: textColor},



];