
// USER ACTIONS
export const AUTH_USER = 'AUTH_USER';

// AUDIO LIST ACTIONS
export const ADD_AUDIO = 'ADD_AUDIO';
export const DELETE_AUDIO = 'DELETE_AUDIO';


// PLAYER ACTIONS
export const SET_PLAYER_STATE = 'SET_PLAYER_STATE';


// PATIENT CODE ACTIONS
export const SET_PATIENT_CODE = 'SET_PATIENT_CODE';

export const OPEN_EDITOR = 'OPEN_EDITOR';

export const CLOSE_EDITOR = 'CLOSE_EDITOR';

// ...