
// USER ACTIONS
export const SET_USER_DATA = 'SET_USER_DATA';

// AUDIO LIST ACTIONS
export const ADD_AUDIO = 'ADD_AUDIO';
export const DELETE_AUDIO = 'DELETE_AUDIO';
export const SET_AUDIOTAG = 'SET_AUDIOTAG';
export const UPDATE_NAME_NEW_AUDIO = 'UPDATE_NAME_NEW_AUDIO';

// PLAYER ACTIONS
export const SET_PLAYER_STATE = 'SET_PLAYER_STATE';

// PATIENT CODE ACTIONS
export const SET_PATIENT_TAG = 'SET_PATIENT_TAG';
export const OPEN_EDITOR = 'OPEN_EDITOR';
export const CLOSE_EDITOR = 'CLOSE_EDITOR';

// HISTORY ACTIONS
export const SET_HISTORY = 'SET_HISTORY';
export const ADD_AUDIO_HISTORY = 'ADD_AUDIO_HISTORY'; 
export const DELETE_AUDIO_HISTORY = 'DELETE_AUDIO_HISTORY';
export const CLEAN_HISTORY = 'CLEAN_HISTORY';

export const UPDATE_DESCRIPTION_AUDIO = 'UPDATE_DESCRIPTION_AUDIO';
export const UPDATE_NAME_AUDIO = 'UPDATE_NAME_AUDIO';

// TAGS ACTIONS
export const ADD_TAG = 'ADD_TAG';
export const CLEAN_TAGS = 'CLEAN_TAGS';
export const SET_CURRENT_TAG_APPLIED = 'SET_CURRENT_TAG_APPLIED';

