
// USER ACTIONS
export const SET_USER_DATA = 'SET_USER_DATA';

// AUDIO LIST ACTIONS
export const ADD_AUDIO = 'ADD_AUDIO';
export const DELETE_AUDIO = 'DELETE_AUDIO';
export const ADD_AUDIOTAG = 'ADD_AUDIOTAG';

// PLAYER ACTIONS
export const SET_PLAYER_STATE = 'SET_PLAYER_STATE';

// PATIENT CODE ACTIONS
export const SET_PATIENT_TAG = 'SET_PATIENT_TAG';

export const OPEN_EDITOR = 'OPEN_EDITOR';

export const CLOSE_EDITOR = 'CLOSE_EDITOR';

// HISTORY ACTIONS
export const SET_HISTORY = 'SET_HISTORY';
export const ADD_AUDIO_HISTORY = 'ADD_AUDIO_HISTORY';
export const CLEAN_HISTORY = 'CLEAN_HISTORY';

// TAGS ACTIONS
export const ADD_TAG = 'ADD_TAG';
export const CLEAN_TAGS = 'CLEAN_TAGS';
export const SET_CURRENT_TAG_APPLIED = 'SET_CURRENT_TAG_APPLIED';

